name: Build, Test, and Push Docker Image to Azure Container Registry

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: restore dependencies
        run: dotnet restore "./week2/Project 1/EventManager.App/EventManager.API"

      - name: build
        run: dotnet build "./week2/Project 1/EventManager.App/EventManager.API" --configuration Release --no-restore

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: log in to acr
        uses: docker/login-action@v3
        with: 
          registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: build and push docker image
        uses: docker/build-push-action@v6
        with: 
          context: .
          file: "./week2/Project 1/EventManager.App/EventManager.API/Dockerfile"
          push: true
          tags: |
            ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/eventmanager-api:latest
            ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/eventmanager-api:${{ github.sha }}
